### ISSUE TITLE
pytorch1.7.0不支持coremltools，但是SiLU又必须用到pytorch1.7.0？

### ISSUE THREAD

**Issue by DaChaoXc** [Wulingtian/yolov5_tensorrt_int8_tools#1]
pytorch1.6.0在不使用leakyReLU和SiLU是可以export的

**Comment by Wulingtian** [comment]
> pytorch1.6.0在不使用leakyReLU和SiLU是可以export的

把他替换为relu就行了

**Comment by DaChaoXc** [comment]
> > pytorch1.6.0在不使用leakyReLU和SiLU是可以export的
> 
> 把他替换为relu就行了

所以你实际使用时是relu替换了两个激活函数（leakyReLU和SiLU）。

**Comment by Wulingtian** [comment]
> > > pytorch1.6.0在不使用leakyReLU和SiLU是可以export的
> > 
> > 
> > 把他替换为relu就行了
> 
> 所以你实际使用时是relu替换了两个激活函数（leakyReLU和SiLU）。

我测试了有无SiLU时，模型精度的变化，最终决定保留，只替换了leakyReLU

**Comment by DaChaoXc** [comment]
> > > > pytorch1.6.0在不使用leakyReLU和SiLU是可以export的
> > > 
> > > 
> > > 把他替换为relu就行了
> > 
> > 
> > 所以你实际使用时是relu替换了两个激活函数（leakyReLU和SiLU）。
> 
> 我测试了有无SiLU时，模型精度的变化，最终决定保留，只替换了leakyReLU

原来是这样啊，回到这个问题，pytorch1.7.0不支持coremltools，但是SiLU又必须用到pytorch1.7.0，或许可以在pytorch里写一个SiLU？

**Comment by Wulingtian** [comment]
> > > > > pytorch1.6.0在不使用leakyReLU和SiLU是可以export的
> > > > 
> > > > 
> > > > 把他替换为relu就行了
> > > 
> > > 
> > > 所以你实际使用时是relu替换了两个激活函数（leakyReLU和SiLU）。
> > 
> > 
> > 我测试了有无SiLU时，模型精度的变化，最终决定保留，只替换了leakyReLU
> 
> 原来是这样啊，回到这个问题，pytorch1.7.0不支持coremltools，但是SiLU又必须用到pytorch1.7.0，或许可以在pytorch里写一个SiLU？

如果你一定要用，那也可以

**Comment by DaChaoXc** [comment]
> > > > > > pytorch1.6.0在不使用leakyReLU和SiLU是可以export的
> > > > > 
> > > > > 
> > > > > 把他替换为relu就行了
> > > > 
> > > > 
> > > > 所以你实际使用时是relu替换了两个激活函数（leakyReLU和SiLU）。
> > > 
> > > 
> > > 我测试了有无SiLU时，模型精度的变化，最终决定保留，只替换了leakyReLU
> > 
> > 
> > 原来是这样啊，回到这个问题，pytorch1.7.0不支持coremltools，但是SiLU又必须用到pytorch1.7.0，或许可以在pytorch里写一个SiLU？
> 
> 如果你一定要用，那也可以

今天仔细看了下，只是coremltool和pytorch1.7.1不适配，并不影响转onnx
